# -*- coding: utf-8 -*-
"""Submission_Deosa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrryRTqD5V11swRUg-B_yCWq6wSZEeDS

# Proyek Analisis Data: [Bike-sharing-dataset]
- **Nama:** [Deosa Putra Caniago]
- **Email:** [deozaofficial@gmail.com]
- **ID Dicoding:** [hid30]

## Menentukan Pertanyaan Bisnis

- 1. Kapan transaksi paling banyak terjadi dalam bulan?
- 2. Hari apa transaksi paling tinggi?

## Import Semua Packages/Library yang Digunakan
"""

!pip install dash gdown plotly

import pandas as pd
import dash
from dash import dcc, html
import plotly.express as px
from dash.dependencies import Input, Output
import numpy as np
import gdown

"""## Data Wrangling

### Gathering Data
"""

# Link Google Drive yang diberikan
url = "https://drive.google.com/uc?id=1oKpEVR_rwshSEdhQrBYuFrspncVclZYw"
output = "all_data.csv"

# Unduh file
gdown.download(url, output, quiet=False)

# Baca dataset
df = pd.read_csv(output)
print(df.head())  # Menampilkan beberapa baris pertama

"""### Assessing Data"""

df.info()
df.describe()

"""### Cleaning Data"""

df['dteday'] = pd.to_datetime(df['dteday'])  # Konversi format tanggal
df['year_month'] = df['dteday'].dt.to_period('M').astype(str)
df['day_of_week'] = df['dteday'].dt.day_name()

df['hour'] = df['hr'] if 'hr' in df.columns else np.nan

"""## Exploratory Data Analysis (EDA)"""

# Pengelompokan data
df_time = df.groupby('year_month', as_index=False).agg({'instant': 'count'})
df_weekday = df.groupby('day_of_week', as_index=False)['instant'].count()
df_season = df.groupby('season', as_index=False)['instant'].count()

# Label musim
season_labels = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
df_season['season'] = df_season['season'].map(season_labels)

"""## Visualization & Explanatory Analysis"""

# Visualisasi transaksi per bulan
fig = px.line(df_time, x='year_month', y='instant', title='Jumlah Transaksi Perbulan')
fig.show()

"""### Pertanyaan 2: Hari apa transaksi paling tinggi?"""

df_weekday = df_weekday.sort_values(by=['instant'], ascending=False)

app = dash.Dash(__name__)

app.layout = html.Div(children=[
    html.H1(children="Bike Sharing Data Analysis"),
    dcc.Graph(
        id='weekday-chart',
        figure=px.bar(
            df_weekday,
            x='day_of_week',
            y='instant',
            title='Penjualan Terbanyak dalam Hari',
            text='instant',
        ).update_traces(
            texttemplate='%{text:,.0f}',
            textposition='outside',
            marker_color=['red' if i == 0 else 'blue' for i in range(len(df_weekday))]
        )
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

"""## Analisis Lanjutan (Opsional): Pengaruh Musim terhadap Jumlah Transaksi"""

app = dash.Dash(__name__)

app.layout = html.Div(children=[
    html.H1(children="Bike Sharing Data Analysis"),
    dcc.Graph(
        id='season-chart',
        figure=px.bar(
            df_season,
            x='season',
            y='instant',
            title='Jumlah Transaksi Berdasarkan Musim'
        ).update_traces(
            marker_color=['red' if val == df_season['instant'].max() else 'blue' for val in df_season['instant']]
        )
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

"""## Conclusion

1. **Kapan transaksi paling banyak terjadi?**
   - Berdasarkan tren jumlah transaksi per bulan, lonjakan transaksi terjadi pada bulan tertentu, kemungkinan karena faktor musiman atau promosi.

2. **Hari apa transaksi paling tinggi?**
   - Dari analisis jumlah transaksi berdasarkan hari dalam seminggu, ditemukan bahwa transaksi tertinggi cenderung terjadi pada hari kerja atau akhir pekan tergantung pada kebiasaan pelanggan.
"""