# -*- coding: utf-8 -*-
"""Submission_Deosa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrryRTqD5V11swRUg-B_yCWq6wSZEeDS

# Proyek Analisis Data: [Bike-sharing-dataset]
- **Nama:** [Deosa Putra Caniago]
- **Email:** [deozaofficial@gmail.com]
- **ID Dicoding:** [hid30]

## Menentukan Pertanyaan Bisnis

- 1. Kapan transaksi paling banyak terjadi dalam bulan?
- 2. Hari apa transaksi paling tinggi?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import gdown

"""## Data Wrangling

### Gathering Data
"""

# Link Google Drive yang diberikan
url = "https://drive.google.com/uc?id=1oKpEVR_rwshSEdhQrBYuFrspncVclZYw"
output = "all_data.csv"

gdown.download(url, output, quiet=False)

# Baca dataset
df = pd.read_csv(output)

"""### Assessing Data
"""

df['dteday'] = pd.to_datetime(df['dteday'])  # Mengecek format tanggal
df['year_month'] = df['dteday'].dt.to_period('M').astype(str)
df['day_of_week'] = df['dteday'].dt.day_name()

if 'hr' in df.columns:
    df['hour'] = df['hr']
else:
    df['hour'] = np.nan

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

df_time = df.groupby('year_month', as_index=False).agg({'instant': 'count'})
df_weekday = df.groupby('day_of_week', as_index=False)['instant'].count()
df_season = df.groupby('season', as_index=False)['instant'].count()

season_labels = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
df_season['season'] = df_season['season'].map(season_labels)

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Kapan transaksi paling banyak terjadi?
"""

st.title("Bike Sharing Data Analysis")
st.subheader("Analisis Transaksi Berdasarkan Waktu")

fig_time = px.line(df_time, x='year_month', y='instant', title='Jumlah Transaksi Perbulan')
st.plotly_chart(fig_time)

"""### Pertanyaan 2: Hari apa transaksi paling tinggi?
"""

df_weekday = df_weekday.sort_values(by=['instant'], ascending=False)
fig_weekday = px.bar(
    df_weekday,
    x='day_of_week',
    y='instant',
    title='Jumlah Transaksi per Hari',
    text='instant',
)
fig_weekday.update_traces(
    texttemplate='%{text:,.0f}',
    textposition='outside',
    marker_color=['red' if i == 0 else 'blue' for i in range(len(df_weekday))]
)
st.plotly_chart(fig_weekday)

"""## Analisis Lanjutan (Opsional) Bagaimana pengaruh musim terhadap jumlah transaksi?
"""

fig_season = px.bar(
    df_season,
    x='season',
    y='instant',
    title='Jumlah Transaksi Berdasarkan Musim'
)
fig_season.update_traces(
    marker_color=['red' if val == df_season['instant'].max() else 'blue' for val in df_season['instant']]
)
st.plotly_chart(fig_season)

"""## Conclusion

- 1. Kapan transaksi paling banyak terjadi?
Berdasarkan analisis tren jumlah transaksi per bulan, transaksi paling banyak terjadi pada bulan-bulan tertentu dengan pola yang dapat diamati. Jika terdapat lonjakan pada bulan tertentu, ini bisa disebabkan oleh faktor musiman, promosi, atau peningkatan aktivitas pelanggan pada periode tersebut.

- 2. Hari apa transaksi paling tinggi?
Dari analisis jumlah transaksi berdasarkan hari dalam seminggu, ditemukan bahwa hari dengan transaksi tertinggi cenderung terjadi pada hari kerja (weekday) atau akhir pekan, tergantung pada jenis bisnisnya. Jika transaksi lebih tinggi pada akhir pekan, ini bisa menunjukkan bahwa pelanggan lebih aktif berbelanja saat libur. Sebaliknya, jika puncaknya terjadi pada hari kerja, mungkin transaksi lebih terkait dengan kebutuhan rutin atau bisnis.
"""